# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c2075245599b251dc4a104330f3b2e9634b5c7b0e81e45b0e501ccae638fea6f1d5d8f45efa2af6006c7fc9ba70c05d76a9ef7a0ae83aaaeb056c6f2dd83b24a

test:
  secret_key_base: c274422b7817d5caea927b7afbf95a79e8db7fe394c4c1b83d71e5f5826092fe5180818fa54939ace63eaa6eba321d6c6ac50a65822348caddf03d11192123eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
